spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hlhlo-job?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
